---

- name: See if com.imobie.AnyTrans directory exists
  stat:
    path: ~/Library/Application Support/com.imobie.AnyTrans
  register: anytrans_config_directory
  tags: [ anytrans ]

- name: Make sure that AnyTrans has been opened at least once
  shell: >
    open -a AnyTrans && sleep 4 && osascript -e 'quit app "AnyTrans"'
  changed_when: false
  when: anytrans_enabled and (not anytrans_config_directory.stat.exists)
  tags: [ anytrans ]

- name: See if we have AnyTrans license entered already
  command: >
    /usr/libexec/PlistBuddy -c "print :RegisteredCode" ~/Library/Application\ Support/com.imobie.AnyTrans/AnyTrans/IMBSoftware-Info.plist
  register: anytrans_existing_license
  failed_when: "'error' in anytrans_existing_license.stderr"
  changed_when: false
  when: anytrans_enabled
  tags: [ anytrans ]

- name: Set AnyTrans License
  command: >
    /usr/libexec/PlistBuddy -c "Set :RegisteredCode {{ anytrans_licensecode }}" ~/Library/Application\ Support/com.imobie.AnyTrans/AnyTrans/IMBSoftware-Info.plist
  when: "(anytrans_enabled) and (anytrans_existing_license.stdout != anytrans_licensecode)"
  tags: [ anytrans ]

- name: Set AnyTrans Registered
  command: >
    /usr/libexec/PlistBuddy -c "Set :IsRegistered true" ~/Library/Application\ Support/com.imobie.AnyTrans/AnyTrans/IMBSoftware-Info.plist
  when: "(anytrans_enabled) and (anytrans_existing_license.stdout != anytrans_licensecode)"
  tags: [ anytrans ]
