---

- name: Ensure Browsers app directory exists
  file:
    path: /Applications/Browsers
    state: directory
  tags: [ browsers ]
  
- name: Ensure Java is installed
  homebrew_cask:
    name: java
    state: present
    
- name: Disable Gatekeeper for macOSa
  shell: >
    sudo spctl --master-disable
  changed_when: false
  args:
    warn: no
